name: eduardoazevedo
description: "Flutter | Dart | C# | Mobile Developer"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.4.1+14

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_animate: ^4.5.0
  url_launcher: ^6.2.5
  flutter_mobx: ^2.2.0+2
  mobx: ^2.3.1
  google_nav_bar: ^5.0.6
  go_router: ^13.2.1
  get_it: ^7.6.7
  flutter_expandable_fab: ^2.0.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.4.0
  build_runner: ^2.4.8
  mobx_codegen: ^2.6.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/languages/
    - assets/images/
    - assets/images/projects/

flutter_native_splash:
  image: "assets/icons/flutter.png"
  color: "#ffffff"
  image_dark: "assets/icons/flutter.png"
  color_dark: "#000000"
