name: eduardoazevedo
description: "Software Engineer | Full Stack Mobile Developer | Flutter & C#"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_animate: ^4.3.0
  url_launcher: ^6.2.1
  flutter_mobx: ^2.2.0
  mobx: ^2.2.1
  google_nav_bar: ^5.0.6
  go_router: ^12.1.1
  get_it: ^7.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.6
  build_runner: ^2.4.7
  mobx_codegen: ^2.4.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

flutter_native_splash:
  image: "assets/icons/flutter.png"
  color: "#ffffff"
  image_dark: "assets/icons/flutter.png"
  color_dark: "#000000"
